---
always_allow_html: yes
---


```{r test_tables, echo=FALSE, message=FALSE}
source("example/R/fcn_documentation.R")

library(kableExtra)
library(dplyr)
library(magrittr)

options(kableExtra.html.bsTable = T)

```

# Customization of MTXQCvX2{#config}

Herein explained are the customizable tables of the MTXQCvX2 universe.

## `conversion_metabolite.csv`


```{r con_se, echo=FALSE}
data = appendix_print("example/tables/config_conse.csv", TRUE)

data %>%
  kable(escape = TRUE, booktabs = TRUE) %>%
  kable_styling(c("striped", "condensed"), 
                 latex_options = "striped", 
                 full_width = TRUE)
```


## `letter_pathway_complete.csv`

```{r metprofile, echo=FALSE}

data = appendix_print("example/tables/config_metprofile.csv", TRUE)
data %>%
  kable(escape = TRUE, booktabs = TRUE) %>%
  kable_styling(c("striped", "condensed"), 
                 latex_options = "striped", 
                 full_width = TRUE)

```

## `quant1-values.csv`

```{r quant1, echo=FALSE}

data = appendix_print("example/tables/config_quant1.csv", TRUE)

data %>%
  kable(escape = TRUE, booktabs = TRUE) %>%
  kable_styling(c("striped", "condensed"), 
                 latex_options = "striped", 
                 full_width = TRUE)

```

## `incorporation_calc.csv` 

```{r inccalc, echo=FALSE}

data = appendix_print("example/tables/config_inccalc.csv", TRUE)

data %>%
  kable(escape = TRUE, booktabs = TRUE) %>%
  kable_styling(c("striped", "condensed"), 
                 latex_options = "striped", 
                 full_width = TRUE)

```

## `mid_backups.csv`

```{r backup, echo=FALSE}

data = appendix_print("example/tables/config_backup.csv", TRUE)

data %>%
  kable(escape = TRUE, booktabs = TRUE) %>%
  kable_styling(c("striped", "condensed"), 
                 latex_options = "striped", 
                 full_width = TRUE)

```


