# Protocols \& Procedures

## Solutions{#solutions}
### Label buffer{#washingbuffer}

Materials:

* ddH2O (500 ml)
* 140 mM NaCl (4.1 g)
* 5 mM Hepes (0.569 g)
* pH calibration 7.4

Procedure:

* Weigh the correct amounts of Hepes and NaCl
* Resolve in a glas bottle with 450 ml of water
* Stir carefully
* Check and adjust pH
* Adjust volumes to 500 ml

### MCW{#mcw}

Materials:

* Methanol
* Chloroform
* ddH2O
* Cinnamic acid stock in MeOH (2 mg/ml): final conc. 2 ug/ml

Procedure:

* Mix the solvents in the ratio of volumes - Methanol:Chlorofom:Water -- 5:2:1
* Supplement cinnamic acid stock 1:1000
* Store at -25&deg;C

### Alkane-Mix{#alkanemix}

Materials:

* Hexane
* Alkanes: c10, c12, c15, c17, c19, c22, c28, c32, c36
* Thermo mixer
* Glass vials and caps

Procedure:

* Prepare stock solutions in hexane:
  + c10 - c17 (liquid): 25 ul/ml
  + c19 - c32: 20 mg/ml
  + c36: two-times 15 mg/1.5 ml
* Warm up alkane stocks in thermo mixer 40&deg;C
* Prepare a text mixture in equal amounts, e.g., 50 ul each, but use twice the volume of c36
* Mix test mixture with MSTFA: 10 ul / 1 ml MSTFA
* Check alkane profile by GC-MS
* If required: adjust volumes and re-test or create larger volume of zour mixture for aliquots
* Store aiquots in glass vials, close well and store at 4&deg;C
* For usage: gently warm up glass vials at 30 C on thermo mixer for 10 min and vortex before adding it to the MSTFA

Adjust the volumes of the alkane stocks in order to create a curve shaped distribution of all alkanes in the chromatogram: lower intensities for c10 and c32-36, slowly increasing intensities for the alkanes in between.

## Idents \& Quant-Standards

has to be written


## Sample Extraction
### Cell extracts

Materials:

- cell culture dishes (10 cm), max. confluency 75\%
- washing buffer (Hepes, NaCl, ph 7.4)
- 50\% MeOH, ice-cold
- 2 mg/ml cinnamic acid
- chloroform
- 15 ml falcon tubes
- cell lifter

Procedure:

- prepare cell culture dishes accordingly to your experimental conditions
- discard cell culture media
- add quickly 5 ml of washing buffer, discard it
- add very immediately 5 ml ice-cold 50\% MeOH suppl. 2 ug/ul cinnamic acid
- detach cells using cell lifter
- collect and transfer cell extract into 15 ml falcon
- store falcons until further processing on ice
- add 1 ml chloroform
- incube for 60 min at cold temperatures (4 C) on rotary or thermo shaker
- centrifuge at max speed for 10 min, cold temperatures
- collect polar and lipid phases into fresh falcons / tubes
- dry under vacuum

In order to generate technical backups:

- resuspend dried extracts in 600 ul 20\% MeOH
- shake at cold temperature on thermo shaker for 30 min
- split volumes into equal parts in fresh eppendorf tubes
- dry under vacuum

Suggested cell density: $2-3e+6$ cells / extract.

### Tissue samples

Materials:

- Methanol:Chloroform:Water (MCW) in ratio 5:2:1
- 2 mg/mg cinnamic acid in MeOH
- ddH20
- eppendorf tubes
- tissue lyzer / pulverizer

Procedure:

- snap-freeze tissue samples
- pulverize samples
- aliquote 50 mg of tissue powder
- add 1.5 ml of MCW (suppl. with cinnamic acid final conc. 2 ug/ul)
- shake for 60 min on rotary shaker at cold temperature (4 C)
- add 0.5 ml ddH20 for phase separation
- centrifuge maximum speed, 10 min, cold temperatures
- collect polar and lipid phases in fresh vessels
- dry under vacuum


### Blood samples

Material:

- Methanol:Chloroform:Water (MCW) in ratio 5:2:1
- 2 mg/mg cinnamic acid in MeOH
- ddH20
- eppendorf tubes 

Procedure:

-	give 20 ul blood / sera directly into 1 ml MCW to avoid lumps
- in case of lumps sonicate samples
- shake samples at 4 C for 800 rpm for 60 min
- add 500 ul ddH20 and vortex shortly
- spin down at 4 C at max speed for 10 min
- aliquote polar phase into 2-3 times 500 ul in 1.5 ml tubes
- aliquote lipid phase 2 times in 100 ul lower in 1.5 ml eppi
- dry in SpeedVac (35 C)

